from __future__ import annotations

import os
import yaml
from datetime import datetime, timezone
from pathlib import Path

import git


PHENOTYPE_LIBRARY_REMOTE = os.environ.get(
    "CRIO_LIBRARY_REMOTE",
    "https://github.com/advocate-phenotype-dev/phenotype-library.git",
)


def _update_timestamp(schema_path: Path) -> dict:
    with open(schema_path) as f:
        schema = yaml.safe_load(f)
    schema["project"]["updated"] = datetime.now(timezone.utc).isoformat()
    with open(schema_path, "w") as f:
        yaml.dump(schema, f, default_flow_style=False, sort_keys=False)
    return schema


def _regenerate_readme(project_dir: Path, schema: dict) -> None:
    ph = schema["phenotype"]
    inv = schema["investigator"]
    comp = schema["compute"]
    readme = f"""# {ph['name']}

**PI:** {inv['pi_name']} ({inv['pi_orcid']})  
**Domain:** {ph['domain']}  
**SCE Tier:** {comp['sce_tier']}  
**Version:** {ph['version']}  
**Status:** {ph['validation_status']}  

## Description

{ph['description']}

## Inclusion Criteria

{ph['inclusion_criteria']}

## Exclusion Criteria

{ph['exclusion_criteria']}

---
*Generated by crio. Do not edit directly — update advocate-phenotype.yaml and run `crio commit`.*
"""
    with open(project_dir / "README.md", "w") as f:
        f.write(readme)


def _update_registry(library_dir: Path, schema: dict) -> None:
    registry_path = library_dir / "registry.yaml"

    if registry_path.exists():
        with open(registry_path) as f:
            registry = yaml.safe_load(f) or {}
    else:
        registry = {}

    projects = registry.get("projects", [])

    project_id = schema["project"]["id"]
    entry = {
        "id": project_id,
        "pi_orcid": schema["investigator"]["pi_orcid"],
        "pi_name": schema["investigator"]["pi_name"],
        "phenotype_name": schema["phenotype"]["name"],
        "domain": schema["phenotype"]["domain"],
        "validation_status": schema["phenotype"]["validation_status"],
        "deposit_eligible": schema["contribution"]["deposit_eligible"],
        "credit_granted": schema["contribution"]["credit_granted"],
        "sce_tier": schema["compute"]["sce_tier"],
        "updated": schema["project"]["updated"],
    }

    # replace existing entry or append
    projects = [p for p in projects if p["id"] != project_id]
    projects.append(entry)

    registry = {
        "generated": datetime.now(timezone.utc).isoformat(),
        "projects": sorted(projects, key=lambda p: p["updated"], reverse=True),
    }

    with open(registry_path, "w") as f:
        yaml.dump(registry, f, default_flow_style=False, sort_keys=False)


def commit(
    project_dir: Path | str,
    library_dir: Path | str,
    message: str,
    sandbox: bool = True,
) -> None:
    """
    Validate, update timestamps, copy project into phenotype-library,
    update registry.yaml, and commit + push.

    In sandbox mode, commits locally but does not push to remote.
    """
    from crio.validate import validate

    project_dir = Path(project_dir)
    library_dir = Path(library_dir)
    schema_path = project_dir / "advocate-phenotype.yaml"

    # validate first — hard stop if invalid
    report = validate(project_dir)
    if not report.valid:
        print("Commit aborted — schema invalid:")
        report.print_report()
        return

    # update timestamp and regenerate README
    schema = _update_timestamp(schema_path)
    _regenerate_readme(project_dir, schema)

    project_id = schema["project"]["id"]

    # copy project into phenotype-library/projects/{uuid}/
    import shutil
    dest = library_dir / "projects" / project_id
    dest.mkdir(parents=True, exist_ok=True)

    for item in project_dir.iterdir():
        if item.name in (".git", ".venv", "__pycache__", ".advocate"):
            continue
        target = dest / item.name
        if item.is_dir():
            if target.exists():
                shutil.rmtree(target)
            shutil.copytree(item, target)
        else:
            shutil.copy2(item, target)

    # update registry
    _update_registry(library_dir, schema)

    # commit to phenotype-library repo
    try:
        repo = git.Repo(library_dir)
    except git.InvalidGitRepositoryError:
        repo = git.Repo.init(library_dir)

    repo.git.add(A=True)

    if repo.is_dirty(index=True):
        repo.index.commit(
            f"[crio] {schema['phenotype']['name']} v{schema['phenotype']['version']}"
            f" ({project_id[:8]}) — {message}"
        )
        print(f"✓ Committed: {message}")
    else:
        print("Nothing to commit — no changes detected")

    if not sandbox:
        origin = repo.remote(name="origin")
        origin.push()
        print("✓ Pushed to remote")
    else:
        print("  Sandbox mode — skipping push")
        print(f"  Library updated at: {library_dir}")
