from __future__ import annotations

import os
import uuid
from datetime import datetime, timezone
from pathlib import Path

import yaml


STUB_DIRS = [
    "src/cohort_definition",
    "src/clarity_queries",
    "src/validation/cohort_diagnostics",
    "src/validation/chart_review",
    "docs",
    ".advocate",
]

GITIGNORE_CONTENT = """.advocate/
*.lock
.env
config/local.*
__pycache__/
*.py[cod]
.DS_Store
"""

README_TEMPLATE = """# {name}

**PI:** {pi_name} ({identifier})
**Role:** {pi_role}
**Domain:** {domain}
**SCE Tier:** {sce_tier}
**Version:** {version}
**Status:** {validation_status}

## Description

{description}

## Inclusion Criteria

{inclusion_criteria}

## Exclusion Criteria

{exclusion_criteria}

---
*Generated by crio. Do not edit directly — update advocate-phenotype.yaml and run `crio commit`.*
"""


def init(
    pi_name: str,
    pi_email: str,
    department: str,
    phenotype_name: str,
    domain: str,
    sce_tier: int,
    data_tier: str,
    environment: str,
    omop_aligned: bool,
    clarity_required: bool,
    description: str,
    inclusion_criteria: str,
    exclusion_criteria: str,
    pi_orcid: str | None = None,
    staff_id: str | None = None,
    pi_role: str = "researcher",
    irb_number: str | None = None,
    irb_status: str | None = None,
    funding_source: str | None = None,
    output_dir: Path | None = None,
) -> Path:
    if not pi_orcid and not staff_id:
        raise ValueError("Must provide either pi_orcid or staff_id")

    identifier = pi_orcid or staff_id
    project_id = str(uuid.uuid4())
    now = datetime.now(timezone.utc).isoformat()

    schema = {
        "project": {
            "id": project_id,
            "created": now,
            "updated": now,
        },
        "investigator": {
            "pi_name": pi_name,
            "pi_email": pi_email,
            "pi_role": pi_role,
            "pi_orcid": pi_orcid,
            "staff_id": staff_id,
            "contributors": [],
        },
        "institution": {
            "department": department,
            "irb_number": irb_number,
            "irb_status": irb_status,
            "funding_source": funding_source,
        },
        "compute": {
            "sce_tier": sce_tier,
            "data_tier": data_tier,
            "environment": environment,
            "requested_at": now,
            "approved_at": None,
            "expires_at": None,
        },
        "phenotype": {
            "name": phenotype_name,
            "version": "0.1.0",
            "domain": domain,
            "omop_aligned": omop_aligned,
            "clarity_required": clarity_required,
            "target_concept_ids": [],
            "icd_codes": [],
            "description": description,
            "inclusion_criteria": inclusion_criteria,
            "exclusion_criteria": exclusion_criteria,
            "validation_status": "draft",
            "validation_method": "none",
            "ppv": None,
            "phekb_id": None,
            "ohdsi_pl_id": None,
        },
        "outputs": {
            "reusable_assets": [],
            "publications": [],
            "downstream_projects": [],
        },
        "contribution": {
            "deposit_eligible": False,
            "deposit_submitted": False,
            "deposit_date": None,
            "credit_granted": False,
        },
    }

    project_dir = Path(output_dir or Path.cwd())
    project_dir.mkdir(parents=True, exist_ok=True)

    for stub in STUB_DIRS:
        (project_dir / stub).mkdir(parents=True, exist_ok=True)

    with open(project_dir / "advocate-phenotype.yaml", "w") as f:
        yaml.dump(schema, f, default_flow_style=False, sort_keys=False)

    with open(project_dir / ".gitignore", "w") as f:
        f.write(GITIGNORE_CONTENT)

    readme = README_TEMPLATE.format(
        name=phenotype_name,
        pi_name=pi_name,
        identifier=identifier,
        pi_role=pi_role,
        domain=domain,
        sce_tier=sce_tier,
        version="0.1.0",
        validation_status="draft",
        description=description,
        inclusion_criteria=inclusion_criteria,
        exclusion_criteria=exclusion_criteria,
    )
    with open(project_dir / "README.md", "w") as f:
        f.write(readme)

    print(f"\n✓ Project initialized · UUID: {project_id}")
    print(f"  Run: crio source\n")
    return project_dir
